jobs:
  main:
    requires: [~commit,~pr]
    steps:
      - printenv
      - sleep 20
    image: node:14
    environment:
      HOGE:
        - ls
        - pwd
      SD_ARTIFACTS_DIR: my_artifacts/
      

